### ISSUE TITLE
code coverage broken

### ISSUE THREAD

**Issue by jodh-intel** [01org/cc-oci-runtime#338]
Configuring like this:

```
./autogen.sh --enable-code-coverage
```

Results in an effectively empty code coverage report after `make check` (only `/usr/*` is included in the report).

**Comment by devimc** [comment]
ummh seems like it was already fixed

**Comment by devimc** [comment]
@jodh-intel   can I close it?

**Comment by jodh-intel** [comment]
Hmm, oddly the reported problem *is* fixed as you say if you don't specify the cov tool. On my system that automatically uses `lcov`.

But listing the cov tool explicitly like this at configure time:

```
./autogen.sh --with-gcov=lcov --enable-code-coverage
```

... results in:

```
  LCOV   --capture cc-oci-runtime-2.1.0-coverage.info
geninfo: WARNING: no .da files found in . - skipping!
  LCOV   --remove /tmp/*
lcov: ERROR: no valid records found in tracefile cc-oci-runtime-2.1.0-coverage.info.tmp

```

**Comment by jcvenegas** [comment]
can we close this issue?

**Comment by jodh-intel** [comment]
Hi @jcvenegas - it's still a problem as shown above if you specify `--with-gcov=lcov`.
